@startuml
abstract class Collectible {
    + spawnPriority : int
    + <<override>> PerformHit(attackedEntity:Entity) : void
    + {abstract} CollectItem(inventory:Inventory) : void
}
Entity <|-- Collectible
@enduml
