@startuml
class HealthBar {
    + healthBarImage : Image
    - trackingHealth : IHealth
    + Initialise(health:IHealth) : void
    - UpdateHealthBar(amount:float) : void
}
MonoBehaviour <|-- HealthBar
@enduml
