@startuml
class Projectile {
    + <<override>> Initialise(player:IPlayerState) : void
    # <<virtual>> KillOnTime() : void
    # <<override>> InitialiseComponents() : void
    + <<override>> PerformHit(attackedEntity:Entity) : void
}
Entity <|-- Projectile
@enduml
